name: GitHub Actions Demo
on:
   push:
    branches:
    - main
jobs:
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'hardhat/README.md'
        destination_repo: 'ethereum-optimism/community-hub'
        destination_folder: 'src/docs/resources/tutorials/hardhat'
        user_email: 'ori@optimism.io'
        user_name: 'Ori Pomerantz'
        commit_message: 'A custom message for the commit'
