name: GitHub Actions Demo
on:
   push:
    branches:
    - main
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clone, copy, and push
      run: |
         CLONE_DIR=/tmp/tmp.EDeCom
         git config --global user.email ori@optimism.io
         git config --global user.name 'Ori Pomerantz'
         git clone --single-branch --branch updated-tutorial https://${{ secrets.API_TOKEN_GITHUB }}:o-auth-basic@github.com/ethereum-optimism/community-hub.git $CLONE_DIR
         cp hardhat/README.md $CLONE_DIR/src/docs/resources/hardhat.md
         cp truffle/README.md $CLONE_DIR/src/docs/resources/truffle.md
         git add .
         git status
         grep -q 'Changes to be committed'
         git commit --message 'Automatic update to keep tutorials in sync'
         git push -u origin HEAD:updated-tutorial
# API_TOKEN_GITHUB: 
